create extension if not exists "uuid-ossp";

create table if not exists produto (
    produto_id uuid not null,
    nome varchar(255) not null,
    categoria varchar(255) not null,
    status varchar(255) not null,
    descricao varchar(255) not null,
    valor numeric(38,2) not null,
    pet_store_pet_id bigint,
    criado_em timestamp(6) not null,
    atualizado_em timestamp(6),
    primary key (produto_id)
);

create table if not exists foto (
    foto_id bigint not null generated by default as identity,
    file_name varchar(255) not null,
    link varchar(255) not null,
    produto_id uuid not null,
    criado_em timestamp(6) not null,
    atualizado_em timestamp(6),
    primary key (produto_id),
    foreign key (produto_id) references produto
);

create table if not exists tag (
    produto_id uuid not null,
    tag varchar(255) not null,
    foreign key (produto_id) references produto
);